services:
  db:
    image: pgvector/pgvector:pg16
    container_name: resume_pg
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: resume
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - resume_pg_data:/var/lib/postgresql/data
volumes:
  resume_pg_data:
